# name: Build Wheels

# on:
#   workflow_dispatch:

# jobs:
#   build:
#     name: Build wheels on ubuntu-latest
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out pdc-dp-means
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2

#       - name: Install build dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install setuptools wheel

#       - name: Build wheels with cibuildwheel
#         uses: pypa/cibuildwheel@v2.12.3
#         with:
#           output-dir: wheelhouse
#         env:
#           CIBW_BUILD: "cp38-* cp39-*"
#           CIBW_BEFORE_BUILD: |
#             pip install -U cython
#             git clone https://github.com/scikit-learn/scikit-learn.git
#             cd scikit-learn
#             git checkout 1.2.X
#             python -m pip install -e .
#             cd ..
#             if [ ! -L sklearn ]; then
#               ln -s scikit-learn/sklearn .
#             fi
#           CIBW_TEST_REQUIRES: pytest numpy scikit-learn
#           CIBW_TEST_COMMAND: pytest {package}/tests

#       - name: Publish artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           path: |
#             ./wheelhouse/*.whl

name: Build Wheels

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # Windows 64 bit
          - os: windows-2019
            python: '38'
            cibw_build: "cp38-*"
          - os: windows-latest
            python: '39'
            cibw_build: "cp39-*"
          - os: windows-latest
            python: '310'
            cibw_build: "cp310-*"
          - os: windows-latest
            python: '311'
            cibw_build: "cp311-*"

          # Linux 64 bit manylinux2014
          - os: ubuntu-latest
            python: '38'
            cibw_build: "cp38-*"
            cibw_image: "manylinux2014"
          - os: ubuntu-latest
            python: '39'
            cibw_build: "cp39-*"
            cibw_image: "manylinux2014"
          - os: ubuntu-latest
            python: '310'
            cibw_build: "cp310-*"
            cibw_image: "manylinux2014"
          - os: ubuntu-latest
            python: '311'
            cibw_build: "cp311-*"
            cibw_image: "manylinux2014"

          # MacOS x86_64
          - os: macos-latest
            python: '38'
            cibw_build: "cp38-*"
          - os: macos-latest
            python: '39'
            cibw_build: "cp39-*"
          - os: macos-latest
            python: '310'
            cibw_build: "cp310-*"
          - os: macos-latest
            python: '311'
            cibw_build: "cp311-*"

    runs-on: ${{ matrix.os }}
    name: Build wheels on ${{ matrix.os }} for Python ${{ matrix.python }}

    steps:
      - name: Check out pdc-dp-means
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v2.12.3
        with:
          output-dir: wheelhouse
        env:
          CIBW_BEFORE_BUILD: |
            pip install -U cython
            git clone https://github.com/scikit-learn/scikit-learn.git
            cd scikit-learn
            git checkout 1.2.X
            python -m pip install -e .
            cd ..
            if [ ! -L sklearn ]; then
              ln -s scikit-learn/sklearn .
            fi
          CIBW_TEST_REQUIRES: pytest numpy scikit-learn
          CIBW_TEST_COMMAND: pytest {package}/tests
          CIBW_BUILD: ${{ matrix.cibw_build }}
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.cibw_image }}

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./wheelhouse/*.whl